image: portal-common-docker.art.rambler.ru/builder

stages:
  - setup

pages:
  stage: setup
  tags:
    - deployer
  only:
    - /^gh-pages$/
  script:
    - mkdir public
    - rsync -rv --exclude=.git --exclude 2.*.* --exclude=node_modules --exclude=public . ./public
  artifacts:
    untracked: false
    paths:
      - 'public'
